Algoritmo "Operadores Aritimeticos"

Var
// Seção de Declarações das variáveis 
   valor1, valor2, valor3, resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Escreva um número: ")
   leia(valor1)
   escreval("Escreva segundo número: ")
   leia(valor2)
   escreval("Escreva terceiro número: ")
   leia(valor3)

   resultado <- (valor1 - valor2) / valor3
   escreval("Resultado: ", resultado)

Fimalgoritmo